import logging
import os

def setup_logger(name=__name__):
    """
    Sets up a logger with a standard format.
    """
    logger = logging.getLogger(name)
    if not logger.handlers:
        logger.setLevel(logging.INFO)
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        
        ch = logging.StreamHandler()
        ch.setFormatter(formatter)
        logger.addHandler(ch)
    return logger

def ensure_directory(path):
    if not os.path.exists(path):
        os.makedirs(path)

def remove_stopwords(text):

    stop_words = {
        "a", "an", "the", "and", "but", "or", "for", "nor", "on", "at", "to", "from", "by", "with", "of",
        "in", "out", "as", "if", "when", "while", "then", "than", "is", "are", "was", "were", "be", "been",
        "being", "have", "has", "had", "do", "does", "did", "can", "could", "will", "would", "shall", "should",
        "may", "might", "must", "it", "its", "this", "that", "these", "those", "i", "you", "he", "she", "we",
        "they", "me", "him", "her", "us", "them", "my", "your", "his", "their", "our", "mine", "yours", "hers",
        "theirs", "ours", "myself", "yourself", "himself", "herself", "itself", "ourselves", "themselves"
    }
    
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return " ".join(filtered_words)

def generate_report_text(title, details, otc_result):
    """
    Generates a formatted text report for the prescription.
    """
    report = []
    report.append("=" * 40)
    report.append(f"MEDICINE REPORT: {title}")
    report.append("=" * 40)
    report.append("\n[PRESCRIPTION DETAILS]")
    report.append(details)
    report.append("\n" + "-" * 40)
    report.append("\n[OTC SAFETY ANALYSIS]")
    
    if "error" in otc_result:
        report.append(f"Error in analysis: {otc_result['error']}")
    else:
        otc_meds = otc_result.get("otc_medicines", [])
        consult_meds = otc_result.get("consult_medicines", [])
        
        if otc_meds:
            report.append("\n✅ Safe to Buy (OTC):")
            for item in otc_meds:
                report.append(f" - {item['name']}: {item['reason']}")
        
        if consult_meds:
            report.append("\n⚠️ Consult Doctor:")
            for item in consult_meds:
                report.append(f" - {item['name']}: {item['reason']}")
                
    report.append("\n" + "=" * 40)
    report.append("Generated by Medi-Mate AI Assistant")
    report.append("DISCLAIMER: This is an AI-generated report. Consult a doctor for medical advice.")
    
    return "\n".join(report)
